version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb
    image: mariadb
    profiles: ["dev", "prod"]
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: R#9aLp2sWu6y
      MYSQL_DATABASE: base_de_datos_de_usuarios
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  users:
    container_name: users
    image: ghcr.io/arquisoft/wiq_es04a/users:latest
    profiles: ["dev", "prod"]
    build: ./users
    depends_on:
      - mariadb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      DATABASE_URL: mariadb:3306/userdb

  questions:
      container_name: questions
      image: ghcr.io/arquisoft/wiq_es04a/questions:latest
      profiles: ["dev", "prod"]
      build: ./questions
      depends_on:
        - mongodb
      ports:
        - "8010:8010"
      networks:
        - mynetwork
      environment:
        DATABASE_URI: mongodb://mongodb:27017/questionDB
        TEST_DATABASE_URI: mongodb://mongodb:27017/test

  gatewayservice:
    container_name: gatewayservice
    image: ghcr.io/arquisoft/wiq_es04a/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - users
      - questions
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      USER_SERVICE_URL: http://users:8001
      QUESTION_SERVICE_URL: http://questions:8010

  webapp:
    container_name: webapp
    image: ghcr.io/arquisoft/wiq_es04a/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
      - gatewayservice
      - multiplayer
    ports:
      - "3000:3000" 
    networks:
      - mynetwork
    environment:
      REACT_APP_API_ENDPOINT: http://gatewayservice:8000
      MULTIPLAYER_ENDPOINT: http://multiplayer:5010

  multiplayer:
    container_name: multiplayer
    image: ghcr.io/arquisoft/wiq_es04a/multiplayer:latest
    profiles: ["dev", "prod"]
    build: ./multiplayer
    depends_on:
      - gatewayservice
    ports:
      - "5010:5010"
    networks:
      - mynetwork
    environment:
      WEBAPP_ENDPOINT: http://webapp:3000
      GATEWAY_SERVICE_ENDPOINT: http://gatewayservice:8000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus

volumes:
  mariadb_data:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
