ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****

Technology decisions

To develop the app we will use the following technologies:

* JavaScript will be the main programming language
* ReactJS to build the user interface
* Docker Compose to deploy all the microservices
* GitHub for version control
* WikiData API to obtain question and answer information

We have considered the trade-offs that belong to each technology, such as SpringBoot or PHP for the backend of the app. 
However, JavaScript was the language that adapted better to our requirements due to the simplicity of the language and its
 focus on agile development that can lead to faster development cycles. 
One of the main disadvantages is that we had to learn it, because our main language is Java. 

Decisions about the top-level decomposition of the system

We decided to use a microservices arquitecture, having different modules for each functionality. 
For example, we will use a microservice to generate the questions.

Decisions on how to achieve key [quality goals](10_quality_requirements.adoc)

[options="header",cols="1,2,2"]
|===
|Quality goal| Decisions to achieve it.
|Usability| We are going to use real users to test the app interface and improve it according to their feedback.
|Availability| Docker Compose will be helpful to avoid problems with the deploy of the app. In addition we will use web hosting to expose it to the internet.
|Security| A login system with encrypted password storage will be used to protect the user data.
|Performance| We will use the minimum required calls to the APIs to mantain the minimum time response, for example, with bulk requests.
|===

Relevant organizational decisions

Our framework will be based on working every week with two weekly meetings, one will be held during lab time in order to assign tasks and make minor decisions.
On the other hand, the weekend meeting will be intended for more thorough reviews as well as more significant decisions.

Each assigned task will be created as an Issue in GitHub to track the progress done. In addition, we are going to use GitHub Projects to organize the workflow of the team.
To merge the code to the develop branch we are going to use Pull Requests in order to be approved by every person of the team.


