ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View

In this Runtime View section, some sequence diagrams of different interactions with the system will be shown.

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****

=== Register Scenario

[plantuml,"Register diagram",png]
----
actor User
participant App
participant GatewayService
participant AuthService
database Database

User -> App: click register link
App --> User: show register view
User -> App: click add user button
App -> GatewayService: addUser()
GatewayService -> AuthService: post('/addUser')
AuthService -> Database: validateRequiredFields()
Database --> AuthService
AuthService --> GatewayService
GatewayService --> App
App --> User
----

=== Login Scenario
[plantuml,"Login diagram",png]
----
actor User
participant App
participant GatewayService
participant UserService
database Database

User -> App: click login link
App --> User: show login view
User -> App: click login button
App -> GatewayService: loginUser()
GatewayService -> UserService: post('/login')
UserService-> Database: validateRequiredFields()
Database --> UserService
UserService--> GatewayService
GatewayService --> App
App --> User
----

=== TBD
