name: Build
on:
  push:
    branches: [master, develop, develop-deploy, develop-teresa]
  
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, develop, develop-deploy]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm --prefix users ci
    - run: npm --prefix questions ci
    - run: npm --prefix gatewayservice ci
    - run: npm --prefix webapp ci
    - run: npm --prefix multiplayer ci
    - run: npm --prefix users test -- --coverage
    - run: npm --prefix questions test -- --coverage
    - run: npm --prefix gatewayservice test -- --coverage
    - run: npm --prefix webapp test -- --coverage
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}